# Generated by Django 5.2 on 2025-04-13 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='selector_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.evaluatoravailability'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='scheduled', max_length=20),
        ),
    ]
